### ISSUE TITLE
How to install on Kodi?

### ISSUE THREAD

**Issue by EtherGhost** [c4valli/kodi-fcast-receiver#10]
How can I install this add-on Kodi?

**Comment by b-risk** [comment]
Hi, I am wondering the same thing, I see some instructions to install it via a terminal but it sounds like a pretty complex thing to do with LibreELEC, which is what I use.

**Comment by aanderse** [comment]
since the addon only uses `python` and `inputstream-adaptive` it is very easy to package for `kodi` (thanks devs!)

simply download the repository and run `make` if you have development tools installed

**Comment by sguerrini97** [comment]
Hi, as said you can run "make" to create a .zip which can be installed via the Kodi interface.
I just published a .zip in the project releases but please keep in mind this addon is still under development and not ready for daily usage.

**Comment by b-risk** [comment]
> Hi, as said you can run "make" to create a .zip which can be installed via the Kodi interface. I just published a .zip in the project releases but please keep in mind this addon is still under development and not ready for daily usage.

Thanks, I was able to connect a flashdrive with the zip on it to my Kodi setup on an Xbox and install it, however when I install it it gives an error but still installs but it doesn't let me run it, did I do something wrong or is it intended behavior? How should I be connecting to it?
